import Background from "@/components/aboutUs/Background"
import Choose from "@/components/aboutUs/choose/Choose"
import Objectives from "@/components/aboutUs/Objectives"
import Appointment from "@/components/overview/Appointment"

export const metadata = {
    title: 'Revive Physiotherapy | About Us',
    description: 'Generated by create next app',
  }

const About = () => {
  return (
    <div className="w-full h-full max-w-7xl mx-auto py-16 px-3 sm:px-4">
      <Background />
      <Objectives />
      <Choose />
      <Appointment />
    </div>
  )
}

export default About