import Whatwedo from "@/components/services/Whatwedo";

export const metadata = {
  title: "Revive Physiotherapy | Our Services",
  description: "Generated by create next app",
};

const Service = () => {
  return(
    <div className="w-full h-full max-w-7xl mx-auto py-16 px-3 sm:px-4">
      <Whatwedo />
    </div>
  )
};

export default Service;
