import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navigation/Navbar";
import Footer from "@/components/Footer";
import Loading from "./loading";
import Chat from "@/components/Chat";


export const metadata = {
  title: "Revive Physiotherapy | Ghana",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <Loading>
        <Navbar />
          {children}
          <Chat />
          <Footer />
        </Loading>
      </body>
    </html>
  );
}
